pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./linux---ubuntu-24_04.html","Linux - Ubuntu 24.04","Einführung Ubuntu 24.04 kann sowohl als Host-System, wie auch in den VMs genutzt werden. Die HOST-Installation sollte ohne Probleme durchführbar s...",""],
["./totp-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; TOTP Structure","Beschreibung TOTP Unterstützung fällt in die Zwei-Faktor-Authentifizierung. Dazu wird für jeden Benutzer ein Secret erstellt und in der Datenbank ...",""],
["./zugriff-auf-objekte-in-der-dat.html","Einige Bemerkungen über Datenbanken","Wie finde ich meine Objekte in der Datenbank ? Die Antwort auf diese Frage ist zentral und man sollte schon einmal darüber genauer nachdenken. Neh...",""],
["./datenbank-restore.html","Gemstone/S-GsDevKit_stones &#62; Datenbank Restore","Geben Sie hier den Text ein.",""],
["./beispiel-user-data.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Vorbereitungen &#62; Beispiel - \"user-data.tpl\"","Konfiguration der einzelnen Maschine  Hier ein Beispiel aus dem mitgelieferten Template. So wird eine Maschine konfiguriert. Neben Java, .Net...",""],
["./licenselist-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; LicenseList Structure","Beschreibung Diese Struktur ermöglicht die Abfrage von Lizenzinformationen (auch mehrere). Die Aufgabe des Entwicklers besteht darin, die verschie...",""],
["./introduction.html","Unterwegs - objekt orientiert ...","Unterwegs in einer Objekt-Orientierten Datenbank",""],
["./beispiel---pas-gemstone_xml.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Vorbereitungen &#62; Beispiel - \"domain.xml.tpl\"","Definition der einzelnen Maschine  Hier ein Beispiel aus dem mitgelieferten Template. So wird eine Maschine definiert. Interessant ist hier d...",""],
["./simple-project-user-role-struc.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Simple Project User Role Structure","Geben Sie hier den Text ein.",""],
["./modell---vorgaben.html","PAS - Softwareentwicklung &#62; Modell Vorgaben","Aufbau der Modelle Wie bereits beschrieben: PUM ist der Kern meiner Entwicklungen. Ich entwerfe mit PUM die Modelle und die APIs. Dabei haben die ...",""],
["./datenbank-anlegen.html","Gemstone/S-GsDevKit_stones &#62; Datenbank anlegen","Geben Sie hier den Text ein.",""],
["./typische-befehle.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Verwaltung und Handling","Typische Befehle Anbei einige typische Befehle, um VMs zu verwalten Alle definierten  VMs anzeigen Um alle registrierten VMs anzuzeigen: &#38;nbs...",""],
["./gemstone---ide.html","Gemstone/S - Datenbank &#62; Gemstone - IDE","Geben Sie hier den Text ein.",""],
["./open-api-support-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Open API Support Structure","Geben Sie hier den Text ein.",""],
["./zeitlicher-stand-der-dokumenta.html","Zeitlicher Stand der Dokumentation","Zeitlicher Stand der Dokumentation  Diese Dokumentation wurde zuletzt am   15.07.2026   bearbeitet. Diese Dokumentation wurde unter...",""],
["./entwicklung---openapi-spezifik.html","Gemstone/S-GsDevKit_stones &#62; Entwicklung - OpenAPI Spezifikation rausschreiben","Publizierung der OpenAPI Spezifikation Nach einer erfolgreichen Migration der Modellstrukturen müssen auch die darauf aufbauenden Strukturen neu b...",""],
["./gemstone---installation.html","Gemstone/S - Datenbank &#62; Gemstone - Installation","Installation Dieser Abschnitt beschreibt nur die Installation von Gemstone im Rahmen des PAS.  Zuerst muß einmal die Runtime-Umgebung für Gem...",""],
["./osm-tile-server.html","OSM Tile Server","Einführung Einige meiner Projekte mit Gemstone/S benutzen Kartendienste, daher kann es sehr wünschenswert sein, so einen OSM-Tile zu installieren....",""],
["./debian-13---trixie.html","Debian 13 - Trixie","Einführung Debian 13 (Trixie) kann mit Gemstone 3.7.5 in den VMs genutzt werden. Ich würde Debian 13 nicht für Anwendungen mit Gemstone/S &#60; 3.7...",""],
["./paslog---sql-datenstruktur.html","PASLOG - Loggen &#62; PASLOG - SQL Datenstruktur","SQL-Tabellenstruktur Die Datenbank besteht aus einer Tabelle, die partitioniert ist über den Zeitstempel (\"MsgClientTs\") der LOG-Meldung...",""],
["./gemstone_s-gsdevkit_stones.html","Gemstone/S-GsDevKit_stones","GsDevKit_stones ist die neue Verwaltungsstruktur, in der Gemstone/S Datenbanken laufen. Diese löst die GsDevKit_home Umgebung ab, die auf 32-Bit A...",""],
["./psql---events.html","PostgreSQL - Datenbank &#62; PSQL - Events","Events für die Anwendungen Neben den Events bei der eigentlichen Anwendung, könnten auch Events notwendig werden, die bei der Speicherung/Änderung...",""],
["./linux-ubuntu-26_04.html","Linux Ubuntu 26.04","Einführung Ubuntu 26.04 sollte noch nicht auf dem HOST installiert werden (aktuelles RabbitMQ fehlt noch). Es gibt noch keine eigene Erfahrung mit...",""],
["./chapter-2.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster","Über die verschiedenen Projekte wurden sehr häufig wiederkehrende Strukturen benötigt. Das führte zu den Strukturen in PUM.",""],
["./openapi.html","OpenAPI","Introduction OpenAPI is a specification for HTTP oriented API definitions The Home Page for OpenAPIs The Home Page For AsyncAPI The Home Page for ...",""],
["./base-rest-api-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; HTTP/RPC API Structure","Diese Struktur beinhaltet die Basis-Strukturen für ein HTTP/RPC orientiertes Projekt. ",""],
["./rest.html","rest","Wo komme ich her ? Wenn man sich bei der Softwareentwicklung neben dem Software-Mainstream aufhält, dann kann das Leben manchmal ganz schön schwie...",""],
["./paslog--installation.html","PASLOG - Loggen &#62; PASLOG - Installation","Geben Sie hier den Text ein.",""],
["./gemstone---sichtweise-unter-kv.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Gemstone - Sichtweise unter KVM","Wie sieht nun die Welt für Gemston/S aus ? Die Datenbank läuft in den VMs. Die HTTP-Antwortprozesse, die SQL-Export Prozesse, die RabbitMQ Verbind...",""],
["./gemstone-statistic-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Gemstone Statistic Structure","Geben Sie hier den Text ein.",""],
["./paslog--c-client-_-knife.html","PASLOG - Loggen &#62; PASLOG - C# Client / Knife","PASLOG  Diese Anwendung stellt in Zusammenhang mit RabbitMQ und einer PostgreSQL Datenbank die Basisstruktur für das zukünftige Logging meine...",""],
["./gemstone---rolle-in-pas.html","Gemstone/S - Datenbank &#62; Gemstone - Rolle in PAS","Rolle im PAS Gemstone/S hat die Rolle der Anwendungsdatenbank in PAS für den laufenden Betrieb. Die Grundidee ist dabei, daß nur der laufende Betr...",""],
["./und-nun-alles-unter-dem-pi.html","Und nun alles unter dem PI","Installation So, und nun die ganze Installation unter einem Raspi PI5/8 GB. Betriebssystem Es wird das Image vom Juni 2026 genutzt mit Debian 13 /...",""],
["./log-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Log Structure","Beschreibung Das Logging-System ermöglicht der Software, Mitteilungen abzuspeichern, damit man später Informationen daraus ziehen kann oder im Feh...",""],
["./pum---rolle-in-pas.html","PUM - Modellierung und Codeerzeugung &#62; PUM - Rolle in PAS","Rolle im PAS PUM ist das zentrale Tool bei der PAS Softwareentwicklung. Alle anderen Tools dienen nur der Durchführung der Arbeit, die ich mir mit...",""],
["./guarded-resource-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Guarded Resource Structure","Geben Sie hier den Text ein.",""],
["./postgresql.html","Linux - Ubuntu 24.04 &#62; PostgreSQL","Einführung In diesem Abschnitt sollen die ersten Punkte im Umgang mit PostgreSQL beschrieben werden. Bis zur Version 22.04 ist PostgreSQL 14 von I...",""],
["./gemstone---eine-lizenzfrage.html","Gemstone/S - Datenbank &#62; Gemstone - Eine Lizenzfrage","Lizenzfrage Bei Gemstone/S muß man immer die Lizenzfrage stellen - um die eigenen Kosten zu reduzieren oder um rechtliche Aspekte zu berücksichtig...",""],
["./paslog---viewer.html","PASLOG - Viewer","Mit Mainstream-Lösungen wäre das nicht passiert Ja, ist wohl so. Der PASLOG-Viewer dient zur Visualisierung der LOG-Daten (neben Superset).  ...",""],
["./pay_python---skripte-und-beisp.html","pas_python - Skripte und Beispielcode","Beschreibung Jedes Projekt bringt seinen eigenen pas_python Ordner mit sich. Er enthält Dateien und Skripte, die für ein spezielles Projekt notwen...",""],
["./datenbank-backup.html","Gemstone/S-GsDevKit_stones &#62; Datenbank Backup","Geben Sie hier den Text ein.",""],
["./ui---sencha-extjs.html","Sencha ExtJS - Schöne UIs","Geben Sie hier den Text ein.",""],
["./single-user-role-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Single User Role Structure","Geben Sie hier den Text ein.",""],
["./entwicklung---api-strukturen-a.html","Gemstone/S-GsDevKit_stones &#62; Entwicklung - API Strukturen auffrischen","Update der API-Struktur Wenn sich mit einer neuen Modellversion die API Struktur verädert hat, dann sollte man interne API Strukturen neu berechne...",""],
["./anlegen-der-datenbank.html","PASLOG-Viewer - Anwendungsbeispiel &#62; Anlegen der Datenbank","Entwicklungsdatenbank anlegen Zuerst einmal machen wir die Gemstone/S Seite fertig. Wir brauchen eine Datebank, in der wir entwickeln. Registry fü...",""],
["./pum---installation.html","PUM - Modellierung und Codeerzeugung &#62; PUM - Installation","Installation Die jeweils aktuelle Version kann man unter   https://feldtmann.ddns.net/pas-project/pum-binaries   herunterladen. Die aktu...",""],
["./pum---modellierung-und-codeerz.html","PUM - Modellierung und Codeerzeugung","Mein Bleistift, mein Spaten, mein Besen Mehr ist zu PUM nicht zusagen.",""],
["./language-text-pool-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Language Text Pool Structure","Beschreibung Diese Struktur liefert die Datenstrukturen, damit ein Server einen Pool von Texten in verschiedenen Sprachen verwalten kann und diese...",""],
["./pas_start_http_task_sh.html","pas_python - Skripte und Beispielcode &#62; pas_start_http_task.sh","Beschreibung Ein Skript, daß einen HTTP Antworttask (Hintergrundprozeß) startet. Wird in der Regel von pas_start_stone_app.sh aufgerufen",""],
["./gsdevkit_stones---installation.html","Gemstone/S-GsDevKit_stones &#62; Installation","Installationsskript herunterladen Das Installationsskript ist natürlich auch in der Umgebung enthalten, aber vor der Installation benötigt man dan...",""],
["./api-encoding---datatypes.html","PAS - Softwareentwicklung &#62; API Encoding - DataTypes","Encoding Time, Date and Timestamps The encoding is done under RFC3339. The fractional part of the seconds should be limited to 3 digits (milliseco...",""],
["./entwicklung---migration-modell.html","Gemstone/S-GsDevKit_stones &#62; Entwicklung - Migration Modellstrukturen","Migration der Modellstrukturen Mit einer Änderung des Modelles geht auch eventuell eine Änderung der Struktur einher. Daher muß eine Migration der...",""],
["./jade---entwicklungs-ide-fuer-g.html","Jade - Entwicklungs IDE für Gemstone/S","Geben Sie hier den Text ein.",""],
["./superset---visualisierung-der-.html","Superset - Visualisierung der Daten","Visualisierung der Daten für den Endbenutzer Daten in der PostgreSQL-Datenbank möchten gerne visualisiert werden. Ich sehe die Daten in der Postgr...",""],
["./public-keys_private-keys.html","Linux - Ubuntu 24.04 &#62; Public Keys/Private Keys","Putty Das Tool putty benötigt immer Dateien im \"ppk\" Format. In dieser Datei sind sowohl der private-Key, wie auch der Public-Key enthal...",""],
["./pattern-rpcjson-errorstructure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; JSON RPC Error Structure","Beschreibung Diese Struktur definiert eine Fehlerklasse, angelehnt an die Fehlerklasse in JSON RPC 2.0. Das muß nun nicht immer sinnvoll sein, abe...",""],
["./events---zusammenarbeit---rabb.html","RabbitMQ - Verteilte Arbeit","In diesem Abschnitt werden spezielle Punkte zu RabbitMQ besprochen.",""],
["./prometheus.html","Prometheus - Erfassung Statistikdaten Softwaresysteme","Rolle im PAS Es kann Softwaresysteme geben, die interne Statistiken sammeln und diese über Prometheus einer Grafana Datenbank zur Verfügung stelle...",""],
["./superset---rolle-in-pas.html","Superset - Visualisierung der Daten &#62; Superset - Rolle in PAS","Rolle im PAS Visualisierung der Daten in der PostgreSQL Datenbank.",""],
["./softwarepackage-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; SoftwarePackageList Structure","Beschreibung Diese Struktur ermöglicht die Abfrage von installierten Software Packages im aktuellen Program. I.d.R. sind Monticello Packages Basis...",""],
["./rmq---rolle-in-pas.html","RabbitMQ - Verteilte Arbeit &#62; RMQ - Rolle in PAS","Rolle im PAS RabbitMQ ist der Datenverteiler in einem verteilten Softwaresystem.  Softwaresysteme wie RabbitMQ oder ZeroMQ sind Augenöffner f...",""],
["./lognotice-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; LogNotice Structure","Geben Sie hier den Text ein.",""],
["./psql---tips-zur-nutzung-und-ko.html","PostgreSQL - Datenbank &#62; PSQL - Tips zur Nutzung und Konfiguration","PostgreSQL - First tips for using psql Starting psql You may start psql fromyour current account via: sudo -u postgres psql Connect to database &#38;l...",""],
["./hintergrundprozesse.html","Hintergrundprozesse","Wenn es zu lange dauert ... Ein API-Call in der Kategorie \"long\" oder \"memory\" sollte trotzdem zügig sein. Synchrone API-Calls...",""],
["./base-stack-model.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Base Stack Model","Beschreibung Diese Struktur lädt die Basiskomponenten eines Entwicklungsstack. Die folgenden Strukturen werden geladen: HTTP/RPC API Structure Eve...",""],
["./login_d.html","Linux - Ubuntu 24.04 &#62; login.d","Hinweise Man muß folgendes berücksichtigen: Die Start-Skripte starten das System als normaler Benutzer und so sollte es sein. In den Linux System ...",""],
["./rmq---installation.html","RabbitMQ - Verteilte Arbeit &#62; RMQ - Installation","Für die Installation schaue bitte in die entsprechende Abschnitte des Betriebssystems.",""],
["./project-user-membership-struct.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Project User Membership Structure","Geben Sie hier den Text ein.",""],
["./gemstone---eine-versionsfrage.html","Gemstone/S - Datenbank &#62; Gemstone - Eine Versionsfrage","Versionsfrage Dieses ganze System berücksichtigt nur die Gemstone/S Version 3.7.5 (Intel/AMD-Linux, ARM-Linux) und neuer. Die Versionsfamilie 3.6....",""],
["./viewer---rolle-in-pas.html","PASLOG - Viewer &#62; Viewer - Rolle in PAS","Rolle im PAS Bei der Visualisierung der LOG-Daten wünsche ich mir ein wenig Komfort. Bis jetzt ist die Visualisierung nur über eine Superset-Insta...",""],
["./base-project-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Base Project Structure","Geben Sie hier den Text ein.",""],
["./shared-memory-einstellungen-im.html","Linux - Ubuntu 24.04 &#62; Shared Memory Einstellungen im HOST und in der VM","Shared Memory im Host und in der VM Gemstone/S ist eine Datenbank und über den SharedMemory können die laufenden \"gems\" sehr schnell auf...",""],
["./kvm.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\"","KVM Infrastruktur Die Nutzung der KVM Infrastruktur wird nur genutzt, um die Lizenzeinschränkungen durch Gemstone/S abzuschwächen. Wir brechen hie...",""],
["./datenbank---postgresql.html","PostgreSQL - Datenbank","PostgreSQL - reicht nicht eine Datenbank ? Was habe ich nicht alles gehört ... \"meine Haupt-DB sei so schlecht, daß er zwei Datenbanken brauc...",""],
["./pumconnector.html","PUMConnector","Einführung Der PUMConnector stellt die Verbindung des PUM Modelling Tools zum Gemstone/S Datenbanksystem her. Es ermöglicht den Transfer von Metho...",""],
["./pas.html","Linux - Ubuntu 24.04 &#62; PAS","Einführung Mit PAS installierst Du die Verwaltungsumgebung von Gemstone/S Datenbanken. Auch wenn wir das eher in den VMs nutzen wollen, liefert es...",""],
["./importieren-der-quelltexte-nac.html","PASLOG-Viewer - Anwendungsbeispiel &#62; Importieren der Quelltexte nach Gemstone","Geben Sie hier den Text ein.",""],
["./installation.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Installation","Vorbedingungen Die folgenden Vorbedingungen sollten erfüllt sein: Nur KVM sollte als Virtualisierung genutzt werden. Keine parallele Installation ...",""],
["./updates-durchfuehren.html","Gemstone/S - Datenbank &#62; Gemstone - Produkt-Updates","Rechtzeitig anfangen Wenn Gemtalk eine neue Version rausgibt, sollte man zügig ein Update seiner Anwendung ausprobieren, um mögliche Probleme rech...",""],
["./password-support-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Password Support Structure","Geben Sie hier den Text ein.",""],
["./paslog---gateway-discord.html","PASLOG - Loggen &#62; PASLOG - Gateway Discord","Discord Es gibt ein Zusatztool, das LOG-Meldungen in einen Discord-Channel kopiert und dort verfügbar macht. Man kann in einer Konfigurationsdatei...",""],
["./verbindung-zur-vm-aufnehmen.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Verbindung zur VM aufnehmen","SSH Verbindung zu den einzelnen VMs aufnehmen Die VMs sind alle nur mit einem NAT als Netzwerk ausgerüstet. Man kann daher mit ssh oder Filezilla ...",""],
["./api-requests.html","API Requests","Effiziente Aufrufe auf eine begrenzte Anzahl von Antwortprozessen",""],
["./pas---softwareentwicklung.html","PAS - Softwareentwicklung","Softwareentwicklung In diesem Abschnitt soll die Softwareentwicklung unter PAS beschrieben werden.",""],
["./base-api-hierarchy-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen (PAS) &#62; Base API Hierarchy Structure","Beschreibung Diese Struktur legt die API Hierarchie an. Ebenso werden die notwendigen Strukturen angelegt, um API Calls ablegen zu können. Diese S...",""],
["./pas_load_appext_sh.html","pas_python - Skripte und Beispielcode &#62; pas_load_appext.sh","Beschreibung Dieses Skript lädt die Anwendungslogik. Diese Skript wird Informationen aus der projektspezifischen \"credentials.sh\" benöti...",""],
["./rabbitmq-und-postgresql-anbind.html","RabbitMQ und PostgreSQL Anbindungen","Transaktionsorientierte Zugriffe Bei der Nutzung von RabbitMQ und PostgreSQL empfehle ich transaktionsorientierte Nutzung. Das bedeutet, dass die ...",""],
["./paslog.html","PASLOG - Loggen","PasLog - Loggen in der Anwendung In diesem Abschnitt soll eine Möglichkeit des Loggens von Nachrichten vorgestellt werden. PASLOG ist ein Framewor...",""],
["./credentials_sh.html","pas_python - Skripte und Beispielcode &#62; credentials.sh","Beschreibung Diese Datei ist die zentrale Konfigurationsdatei einer Anwendung: sie dient der Konfiguration von projektspezifischen Namen und Einst...",""],
["./linux-allgemein.html","Linux - Ubuntu 24.04 &#62; Linux Allgemein","Update software packages The next step is to update the package system and install all pending updates: sudo apt-get update  sudo apt-get upg...",""],
["./gemstone---crontabs.html","Gemstone/S - Datenbank &#62; Gemstone - Crontabs, Backup, GC","Regelmäßige Aufgaben - crontabs Unter Linux werden regelmäßig auszuführende Aufgaben als Jobs in einer sogenannten crontab-Datei definiert. Bei Ge...",""],
["./datenbank---gemsdtone_s.html","Gemstone/S - Datenbank","Gemstone/S - ein OODBMS System als Basis ? Holy Schitt ... da benutzt noch jemand eine OODBMS - ein Relikt aus den achtziger Jahre. Kein Mainstrea...",""],
["./sftp-upload-only-service.html","Linux - Ubuntu 24.04 &#62; SFTP Upload-Only Service","Introduction sftp based file transfers should be made possible. So here a description how to do that. We create user, who is only allowed to uploa...",""],
["./entwicklung---neues-model-lade.html","Gemstone/S-GsDevKit_stones &#62; Entwicklung - Neues Model laden","Einführung PUM erzeugt eine neue Modellbeschreibung Ihrer Datenbank in der internen Sprache \"topaz\". Das ist ein Dialekt der Programmier...",""],
["./extjs---rolle-in-pas.html","Sencha ExtJS - Schöne UIs &#62; ExtJS - Rolle in PAS","Rolle im PAS Sencha ExtJS ist ein Javascript-System zur Programmierung von Benutzeroberflächen, die im Browser ablaufen.  Die Bibliothek ist ...",""],
["./ein-modell-muss-her-___.html","PASLOG-Viewer - Anwendungsbeispiel &#62; Ein Modell muß her ...","Wie ? Kein Editor ? So, der Mainstream holt sich einen Editor und tippt den Code ein oder wirft eine KI an und hofft dann, Teile davon nutzbar zu ...",""],
["./gemstone---linux-service-suppo.html","Gemstone/S - Datenbank &#62; Gemstone - Linux-Service Support","Start-/Stopskripte Zum Starten und Stoppen einer PAS Anwendung als Service muß man aus dem Checkout des GsDevKit_stones im Unterverzeichnis \"...",""],
["./quelltexte-erzeugen-fuer-gemst.html","PASLOG-Viewer - Anwendungsbeispiel &#62; Quelltexte erzeugen für Gemstone/S","Geben Sie hier den Text ein.",""],
["./gemstone---restore.html","Gemstone/S - Datenbank &#62; Gemstone - Restore","Ein Backup einspielen Ein Backup einzuspielen kann in drei Fällen notwendig sein: Es ist ein Fehler aufgetreten und dieser kann nur durch ein Rest...",""],
["./apache2.html","Linux - Ubuntu 24.04 &#62; Apache2","Einführung In diesem Abschnitt sollen vor allem die Module betrachtet werden, die benötigt werden. Installation Man beachte das Installationsscrip...",""],
["./paslog--rolle-in-pas.html","PASLOG - Loggen &#62; PASLOG - Rolle in PAS","Rolle im PAS PASLOG ist eine LOG-Schnittstelle, die man in PAS-Anwendungen nutzen kann. Natürlich hat Gemstone/S eine normale TextLogging Möglichk...",""],
["./pas_load_appprereq_sh.html","pas_python - Skripte und Beispielcode &#62; pas_load_appprereq.sh","Beschreibung Dieses Skript lädt Pakete, die für die App benötigt werden, aber nicht Bestandteil der Runtime sind (bzw. noch nicht sind). Dieses Sk...",""],
["./event-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Event Structure","Beschreibung Diese Struktur ermöglicht das Senden eines Events auf den Eventbus (und damit über RabbitMQ). Die Struktur stellt einen API-Call Send...",""],
["./pas_initialize_application_sh.html","pas_python - Skripte und Beispielcode &#62; pas_init_appdata.sh","Beschreibung Dieses Skript soll die Datenstrukturen für die Anwendung initialisieren. Diese Anwendung wird Informationen aus der projektspezifisch...",""],
["./customer-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Customer Structure","Geben Sie hier den Text ein.",""],
["./vorbereitungen.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Vorbereitungen","Template Mit dem Checkout von meiner Variante von GsDevKit_stones gibt es auch ein Template im Unterverzeichnis \"kvm-support\", um ein Tr...",""],
["./gemstone---eine-paketfrage.html","Gemstone/S - Datenbank &#62; Gemstone - Eine Paketfrage","Paketfrage Dieses System unterstützt nur Quelltextpakete im Monticello/Metacello Format. Der Anbieter liefert mit jeder Produktversion ein Seaside...",""],
["./vm-clients---betriebssysteme.html","Linux - Ubuntu 24.04 &#62; KVM - Gemstone \"Carrier\" &#62; Vorbereitungen &#62; VM Clients - Betriebssysteme","VM Clients Für Gemstone-Instanzen gilt: ab Gemstone/S 3.6.5 sollte Ubuntu gewählt werden - hier wird 22.04, 24.04 unterstützt (nicht alles geteste...",""],
["./strukturen-(pas).html","PUM - Modellierung und Codeerzeugung &#62; Strukturen (PAS)","Geben Sie hier den Text ein.",""],
["./paslog-viewer---anwendungsbeis.html","PASLOG-Viewer - Anwendungsbeispiel","Zielsetzung Viel nachgedacht habe ich nicht, als ich diese Anwendungsentwicklung gestartet hatte. Am Anfang wurden folgendes angenommen: Eigenstän...",""],
["./pas_load_application_sh.html","pas_python - Skripte und Beispielcode &#62; pas_load_appmodel.sh","Beschreibung Dieses Skript lädt NUR das Monticello-Paket, das das persistente Modell und die API Strukturen definieren.  Dieses Paket resulti...",""],
["./psql---rolle-in-pas.html","PostgreSQL - Datenbank &#62; PSQL - Rolle in PAS","Rolle im PAS PostgreSQL ist die sekundäre Datenbank in PAS. Ich nutze diese Datenbanken unter mehreren Aspekten. Regelmäßiger direkter Export nach...",""],
["./datenbank(pas)-anlegen.html","Gemstone/S-GsDevKit_stones &#62; Datenbank (PAS) anlegen","Einführung Zuerst wird eine neue Datenbank aus den mitgelieferten Seaside-Template (Monticello) der Gemstone erzeugt.   pas_create_pas_stone....",""],
["./prelogin-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; PreLogin Structure","Beschreibung Dieses Package definiert einen Support vor einem Login - so daß man den Login-Dialog entsprechend darstellen kann. Dieser Dialog kann...",""],
["./dotnet-core-6_0_x.html","Linux - Ubuntu 24.04 &#62; DotNet Core","Einführung Die Installation für .Net Core unter Ubuntu ist hier beschrieben. Außerdem kann man die einzelne Befehle in dem Konfigurationstemplate ...",""],
["./pas_start_stone_app_sh.html","pas_python - Skripte und Beispielcode &#62; pas_start_stone_app.sh","Beschreibung Ein Skript, das die komplette Anwendung startet. Dieses Skript wird auch bei der Ausführung von service-Diensten (service im Sinne vo...",""],
["./api-richtlinien.html","PAS - Softwareentwicklung &#62; API Vorgaben","Implementierungen der API Jeder API Call erhält in PUM folgende Informationen Der Call erhält eine Aufrufparameter-Struktur. Diese Struktur ist al...",""],
["./pas---pum-application-stack.html","PAS - PUM Application Stack","PAS - der Application Stack Während meiner Arbeit mit Gemstone/S hat es sich gezeigt, daß ich immer wieder und wieder die gleichen Komponenten ein...",""],
["./session-activitystructure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Session ActivityStructure","Geben Sie hier den Text ein.",""],
["./psql---installation.html","PostgreSQL - Datenbank &#62; PSQL - Installation","Installation Die Installation unterscheidet sich, ob man einen lokalen oder einen entfernten Datenbank-Server nutzen will. Eine genauere Beschreib...",""],
["./rabbitmq.html","Linux - Ubuntu 24.04 &#62; RabbitMQ","Einführung RabbitMQ ist ein Verteiler von Nachrichten. Über RabbitMQ kann man Programme in verschiedenen Programmiersprachen kommunizieren lassen....",""],
["./pas_stop_stone_app_sh.html","pas_python - Skripte und Beispielcode &#62; pas_stop_stone_app.sh","Beschreibung Ein Skript, das die komplette Anwendung herunterfährt. Dieses Skript wird auch bei der Ausführung von service-Diensten (service im Si...",""],
["./grafana---visualisierungen-sof.html","Grafana - Visualisierungen Softwaresysteme","Rolle im PAS Grafana wird genutzt, um Informationen von Anwendungen zu sammeln und diese zu visualisieren. Die Daten können von Prometheus eingesa...",""],
["./session-support-structure.html","PUM - Modellierung und Codeerzeugung &#62; Strukturen und Muster &#62; Session Support Structure","Beschreibung Diese Struktur ermöglicht die Bearbeitung von Benutzer-Sessions. Beispielimplementierung Benutzer loggt sich ein - Smalltalk - Server...",""]];
